using System;

namespace Portico;

/// <summary>
/// Unit-like marker type for presence-only command-line <b>switches</b> (flags). A switch is
/// either supplied or absent — it carries no value. This is categorically different from a
/// boolean option: <c>--verbose</c> is a switch; <c>--logging enabled|disabled</c> is a
/// two-state scalar that happens to parse to <see cref="bool"/>.
/// </summary>
/// <remarks>
/// <para>
/// Declare a switch as <c>CliFlag? verbose</c>. When the flag is supplied on the command line the
/// materialized value is <see cref="Default"/>; when it is absent the value is <c>null</c>.
/// Switch parameters never carry a value; providing <c>--verbose true</c> is a usage error.
/// </para>
/// <para>
/// <b>Design intent.</b> Portico distinguishes switches from boolean scalars because conflating
/// them hurts the model: users typing <c>bool x</c> would be surprised that <c>--x true</c> is
/// rejected at parse time. Keeping <see cref="CliFlag"/> as the only flag type — and routing
/// <see cref="bool"/> through the scalar path — makes both cases work as the user expects.
/// </para>
/// <para>
/// Equality is auto-generated by the <c>record struct</c> (field-by-field on a zero-field struct
/// → always equal). Test presence with <c>CliFlag?.HasValue</c>; don't compare instances.
/// </para>
/// </remarks>
public readonly record struct CliFlag
{
    /// <summary>The canonical "switch-was-supplied" value.</summary>
    public static readonly CliFlag Default = default;

    /// <summary>
    /// True iff <paramref name="type"/> is the presence-marker type (<see cref="CliFlag"/> or
    /// <c>CliFlag?</c>). <see cref="bool"/> and <c>bool?</c> are <em>not</em> flag types — they
    /// route through the scalar materializer, which parses <c>"true"</c>/<c>"false"</c> via the
    /// registered <see cref="System.ComponentModel.TypeConverter"/>.
    /// </summary>
    internal static bool IsFlagType(Type type, out object presentValue)
    {
        var underlyingType = Nullable.GetUnderlyingType(type) ?? type;
        if (underlyingType == typeof(CliFlag))
        {
            presentValue = Default;
            return true;
        }
        presentValue = Default;
        return false;
    }

    /// <summary>Returns the literal <c>"flag"</c>. A switch has no distinguishing value.</summary>
    public override string ToString() => "flag";
}
